name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  solution: ./Bytz.Collections.Dispatch.sln
  packageDir: ./Bytz.Collections.Dispatch/pkgs

jobs:
  build:
    env:
      buildVersion: '7.0.${{github.run_number}}'
      nugetAuthToken: ${{ bytz.collections.dispatch }}
    
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build for Release
      run: dotnet build --no-restore -c Release --version-suffix $buildVersion $solution
    
    - name: Package Assemblies
      run: dotnet pack --no-build $solution -p:PackageVersion=$buildVersion -o $packageDir
      
    - name: Push Packages to Repository
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k $nugetAuthToken --skip-duplicate $packageDir/**/*.nupkg
      

